#ifndef STEAM_API_H
#define STEAM_API_H

// Basic Steam API interface definitions
typedef unsigned int uint32;
typedef unsigned short uint16;
typedef unsigned long long uint64;
typedef unsigned char uint8;

// Steam API return values
enum ESteamAPIInitResult
{
    k_ESteamAPIInitResult_OK = 0,
    k_ESteamAPIInitResult_FailedGeneric = 1,
    k_ESteamAPIInitResult_NoSteamClient = 2,
    k_ESteamAPIInitResult_VersionMismatch = 3,
};

// Steam server mode
enum EServerMode
{
    eServerModeInvalid = 0,
    eServerModeNoAuthentication = 1,
    eServerModeAuthentication = 2,
    eServerModeAuthenticationAndSecure = 3,
};

// Steam interface versions
#define STEAMCLIENT_INTERFACE_VERSION_001 "SteamClient001"
#define STEAMCLIENT_INTERFACE_VERSION_002 "SteamClient002"
#define STEAMCLIENT_INTERFACE_VERSION_003 "SteamClient003"
#define STEAMCLIENT_INTERFACE_VERSION_004 "SteamClient004"
#define STEAMCLIENT_INTERFACE_VERSION_005 "SteamClient005"
#define STEAMCLIENT_INTERFACE_VERSION_006 "SteamClient006"
#define STEAMCLIENT_INTERFACE_VERSION_007 "SteamClient007"
#define STEAMCLIENT_INTERFACE_VERSION_008 "SteamClient008"
#define STEAMCLIENT_INTERFACE_VERSION_009 "SteamClient009"
#define STEAMCLIENT_INTERFACE_VERSION_010 "SteamClient010"
#define STEAMCLIENT_INTERFACE_VERSION_011 "SteamClient011"
#define STEAMCLIENT_INTERFACE_VERSION_012 "SteamClient012"
#define STEAMCLIENT_INTERFACE_VERSION_013 "SteamClient013"
#define STEAMCLIENT_INTERFACE_VERSION_014 "SteamClient014"
#define STEAMCLIENT_INTERFACE_VERSION_015 "SteamClient015"
#define STEAMCLIENT_INTERFACE_VERSION_016 "SteamClient016"
#define STEAMCLIENT_INTERFACE_VERSION_017 "SteamClient017"
#define STEAMCLIENT_INTERFACE_VERSION_018 "SteamClient018"
#define STEAMCLIENT_INTERFACE_VERSION_019 "SteamClient019"
#define STEAMCLIENT_INTERFACE_VERSION_020 "SteamClient020"
#define STEAMUSER_INTERFACE_VERSION_001 "SteamUser001"
#define STEAMUSER_INTERFACE_VERSION_002 "SteamUser002"
#define STEAMUSER_INTERFACE_VERSION_003 "SteamUser003"
#define STEAMUSER_INTERFACE_VERSION_004 "SteamUser004"
#define STEAMUSER_INTERFACE_VERSION_005 "SteamUser005"
#define STEAMUSER_INTERFACE_VERSION_006 "SteamUser006"
#define STEAMUSER_INTERFACE_VERSION_007 "SteamUser007"
#define STEAMUSER_INTERFACE_VERSION_008 "SteamUser008"
#define STEAMUSER_INTERFACE_VERSION_009 "SteamUser009"
#define STEAMUSER_INTERFACE_VERSION_010 "SteamUser010"
#define STEAMUSER_INTERFACE_VERSION_011 "SteamUser011"
#define STEAMUSER_INTERFACE_VERSION_012 "SteamUser012"
#define STEAMUSER_INTERFACE_VERSION_013 "SteamUser013"
#define STEAMUSER_INTERFACE_VERSION_014 "SteamUser014"
#define STEAMUSER_INTERFACE_VERSION_015 "SteamUser015"
#define STEAMUSER_INTERFACE_VERSION_016 "SteamUser016"
#define STEAMUSER_INTERFACE_VERSION_017 "SteamUser017"
#define STEAMUSER_INTERFACE_VERSION_018 "SteamUser018"
#define STEAMUSER_INTERFACE_VERSION_019 "SteamUser019"
#define STEAMUSER_INTERFACE_VERSION_020 "SteamUser020"
#define STEAMUSER_INTERFACE_VERSION_021 "SteamUser021"
#define STEAMUSER_INTERFACE_VERSION_022 "SteamUser022"
#define STEAMFRIENDS_INTERFACE_VERSION_001 "SteamFriends001"
#define STEAMFRIENDS_INTERFACE_VERSION_002 "SteamFriends002"
#define STEAMFRIENDS_INTERFACE_VERSION_003 "SteamFriends003"
#define STEAMFRIENDS_INTERFACE_VERSION_004 "SteamFriends004"
#define STEAMFRIENDS_INTERFACE_VERSION_005 "SteamFriends005"
#define STEAMFRIENDS_INTERFACE_VERSION_006 "SteamFriends006"
#define STEAMFRIENDS_INTERFACE_VERSION_007 "SteamFriends007"
#define STEAMFRIENDS_INTERFACE_VERSION_008 "SteamFriends008"
#define STEAMFRIENDS_INTERFACE_VERSION_009 "SteamFriends009"
#define STEAMFRIENDS_INTERFACE_VERSION_010 "SteamFriends010"
#define STEAMFRIENDS_INTERFACE_VERSION_011 "SteamFriends011"
#define STEAMFRIENDS_INTERFACE_VERSION_012 "SteamFriends012"
#define STEAMFRIENDS_INTERFACE_VERSION_013 "SteamFriends013"
#define STEAMFRIENDS_INTERFACE_VERSION_014 "SteamFriends014"
#define STEAMFRIENDS_INTERFACE_VERSION_015 "SteamFriends015"
#define STEAMFRIENDS_INTERFACE_VERSION_016 "SteamFriends016"
#define STEAMFRIENDS_INTERFACE_VERSION_017 "SteamFriends017"
#define STEAMUTILS_INTERFACE_VERSION_001 "SteamUtils001"
#define STEAMUTILS_INTERFACE_VERSION_002 "SteamUtils002"
#define STEAMUTILS_INTERFACE_VERSION_003 "SteamUtils003"
#define STEAMUTILS_INTERFACE_VERSION_004 "SteamUtils004"
#define STEAMUTILS_INTERFACE_VERSION_005 "SteamUtils005"
#define STEAMUTILS_INTERFACE_VERSION_006 "SteamUtils006"
#define STEAMUTILS_INTERFACE_VERSION_007 "SteamUtils007"
#define STEAMUTILS_INTERFACE_VERSION_008 "SteamUtils008"
#define STEAMUTILS_INTERFACE_VERSION_009 "SteamUtils009"
#define STEAMMATCHMAKING_INTERFACE_VERSION_001 "SteamMatchMaking001"
#define STEAMMATCHMAKING_INTERFACE_VERSION_002 "SteamMatchMaking002"
#define STEAMMATCHMAKING_INTERFACE_VERSION_003 "SteamMatchMaking003"
#define STEAMMATCHMAKING_INTERFACE_VERSION_004 "SteamMatchMaking004"
#define STEAMMATCHMAKING_INTERFACE_VERSION_005 "SteamMatchMaking005"
#define STEAMMATCHMAKING_INTERFACE_VERSION_006 "SteamMatchMaking006"
#define STEAMMATCHMAKING_INTERFACE_VERSION_007 "SteamMatchMaking007"
#define STEAMMATCHMAKING_INTERFACE_VERSION_008 "SteamMatchMaking008"
#define STEAMMATCHMAKING_INTERFACE_VERSION_009 "SteamMatchMaking009"
#define STEAMUSERSTATS_INTERFACE_VERSION_001 "STEAMUSERSTATS_INTERFACE_VERSION001"
#define STEAMUSERSTATS_INTERFACE_VERSION_002 "STEAMUSERSTATS_INTERFACE_VERSION002"
#define STEAMUSERSTATS_INTERFACE_VERSION_003 "STEAMUSERSTATS_INTERFACE_VERSION003"
#define STEAMUSERSTATS_INTERFACE_VERSION_004 "STEAMUSERSTATS_INTERFACE_VERSION004"
#define STEAMUSERSTATS_INTERFACE_VERSION_005 "STEAMUSERSTATS_INTERFACE_VERSION005"
#define STEAMUSERSTATS_INTERFACE_VERSION_006 "STEAMUSERSTATS_INTERFACE_VERSION006"
#define STEAMUSERSTATS_INTERFACE_VERSION_007 "STEAMUSERSTATS_INTERFACE_VERSION007"
#define STEAMUSERSTATS_INTERFACE_VERSION_008 "STEAMUSERSTATS_INTERFACE_VERSION008"
#define STEAMUSERSTATS_INTERFACE_VERSION_009 "STEAMUSERSTATS_INTERFACE_VERSION009"
#define STEAMUSERSTATS_INTERFACE_VERSION_010 "STEAMUSERSTATS_INTERFACE_VERSION010"
#define STEAMUSERSTATS_INTERFACE_VERSION_011 "STEAMUSERSTATS_INTERFACE_VERSION011"
#define STEAMUSERSTATS_INTERFACE_VERSION_012 "STEAMUSERSTATS_INTERFACE_VERSION012"
#define STEAMAPPS_INTERFACE_VERSION_001 "STEAMAPPS_INTERFACE_VERSION001"
#define STEAMAPPS_INTERFACE_VERSION_002 "STEAMAPPS_INTERFACE_VERSION002"
#define STEAMAPPS_INTERFACE_VERSION_003 "STEAMAPPS_INTERFACE_VERSION003"
#define STEAMAPPS_INTERFACE_VERSION_004 "STEAMAPPS_INTERFACE_VERSION004"
#define STEAMAPPS_INTERFACE_VERSION_005 "STEAMAPPS_INTERFACE_VERSION005"
#define STEAMAPPS_INTERFACE_VERSION_006 "STEAMAPPS_INTERFACE_VERSION006"
#define STEAMAPPS_INTERFACE_VERSION_007 "STEAMAPPS_INTERFACE_VERSION007"
#define STEAMAPPS_INTERFACE_VERSION_008 "STEAMAPPS_INTERFACE_VERSION008"
#define STEAMNETWORKING_INTERFACE_VERSION_001 "SteamNetworking001"
#define STEAMNETWORKING_INTERFACE_VERSION_002 "SteamNetworking002"
#define STEAMNETWORKING_INTERFACE_VERSION_003 "SteamNetworking003"
#define STEAMNETWORKING_INTERFACE_VERSION_004 "SteamNetworking004"
#define STEAMNETWORKING_INTERFACE_VERSION_005 "SteamNetworking005"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_001 "STEAMREMOTESTORAGE_INTERFACE_VERSION001"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_002 "STEAMREMOTESTORAGE_INTERFACE_VERSION002"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_003 "STEAMREMOTESTORAGE_INTERFACE_VERSION003"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_004 "STEAMREMOTESTORAGE_INTERFACE_VERSION004"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_005 "STEAMREMOTESTORAGE_INTERFACE_VERSION005"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_006 "STEAMREMOTESTORAGE_INTERFACE_VERSION006"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_007 "STEAMREMOTESTORAGE_INTERFACE_VERSION007"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_008 "STEAMREMOTESTORAGE_INTERFACE_VERSION008"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_009 "STEAMREMOTESTORAGE_INTERFACE_VERSION009"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_010 "STEAMREMOTESTORAGE_INTERFACE_VERSION010"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_011 "STEAMREMOTESTORAGE_INTERFACE_VERSION011"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_012 "STEAMREMOTESTORAGE_INTERFACE_VERSION012"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_013 "STEAMREMOTESTORAGE_INTERFACE_VERSION013"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_014 "STEAMREMOTESTORAGE_INTERFACE_VERSION014"
#define STEAMREMOTESTORAGE_INTERFACE_VERSION_015 "STEAMREMOTESTORAGE_INTERFACE_VERSION015"
#define STEAMSCREENSHOTS_INTERFACE_VERSION_001 "STEAMSCREENSHOTS_INTERFACE_VERSION001"
#define STEAMSCREENSHOTS_INTERFACE_VERSION_002 "STEAMSCREENSHOTS_INTERFACE_VERSION002"
#define STEAMSCREENSHOTS_INTERFACE_VERSION_003 "STEAMSCREENSHOTS_INTERFACE_VERSION003"
#define STEAMHTTP_INTERFACE_VERSION_001 "STEAMHTTP_INTERFACE_VERSION001"
#define STEAMHTTP_INTERFACE_VERSION_002 "STEAMHTTP_INTERFACE_VERSION002"
#define STEAMHTTP_INTERFACE_VERSION_003 "STEAMHTTP_INTERFACE_VERSION003"
#define STEAMUNIFIEDMESSAGES_INTERFACE_VERSION_001 "STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001"
#define STEAMCONTROLLER_INTERFACE_VERSION_001 "SteamController001"
#define STEAMCONTROLLER_INTERFACE_VERSION_003 "SteamController003"
#define STEAMCONTROLLER_INTERFACE_VERSION_004 "SteamController004"
#define STEAMCONTROLLER_INTERFACE_VERSION_005 "SteamController005"
#define STEAMCONTROLLER_INTERFACE_VERSION_006 "SteamController006"
#define STEAMCONTROLLER_INTERFACE_VERSION_007 "SteamController007"
#define STEAMUGC_INTERFACE_VERSION_001 "STEAMUGC_INTERFACE_VERSION001"
#define STEAMUGC_INTERFACE_VERSION_002 "STEAMUGC_INTERFACE_VERSION002"
#define STEAMUGC_INTERFACE_VERSION_003 "STEAMUGC_INTERFACE_VERSION003"
#define STEAMUGC_INTERFACE_VERSION_004 "STEAMUGC_INTERFACE_VERSION004"
#define STEAMUGC_INTERFACE_VERSION_005 "STEAMUGC_INTERFACE_VERSION005"
#define STEAMUGC_INTERFACE_VERSION_006 "STEAMUGC_INTERFACE_VERSION006"
#define STEAMUGC_INTERFACE_VERSION_007 "STEAMUGC_INTERFACE_VERSION007"
#define STEAMUGC_INTERFACE_VERSION_008 "STEAMUGC_INTERFACE_VERSION008"
#define STEAMUGC_INTERFACE_VERSION_009 "STEAMUGC_INTERFACE_VERSION009"
#define STEAMUGC_INTERFACE_VERSION_010 "STEAMUGC_INTERFACE_VERSION010"
#define STEAMUGC_INTERFACE_VERSION_011 "STEAMUGC_INTERFACE_VERSION011"
#define STEAMUGC_INTERFACE_VERSION_012 "STEAMUGC_INTERFACE_VERSION012"
#define STEAMUGC_INTERFACE_VERSION_013 "STEAMUGC_INTERFACE_VERSION013"
#define STEAMUGC_INTERFACE_VERSION_014 "STEAMUGC_INTERFACE_VERSION014"
#define STEAMUGC_INTERFACE_VERSION_015 "STEAMUGC_INTERFACE_VERSION015"
#define STEAMUGC_INTERFACE_VERSION_016 "STEAMUGC_INTERFACE_VERSION016"
#define STEAMUGC_INTERFACE_VERSION_017 "STEAMUGC_INTERFACE_VERSION017"
#define STEAMUGC_INTERFACE_VERSION_018 "STEAMUGC_INTERFACE_VERSION018"
#define STEAMUGC_INTERFACE_VERSION_019 "STEAMUGC_INTERFACE_VERSION019"
#define STEAMUGC_INTERFACE_VERSION_020 "STEAMUGC_INTERFACE_VERSION020"
#define STEAMAPPLIST_INTERFACE_VERSION_001 "STEAMAPPLIST_INTERFACE_VERSION001"
#define STEAMMUSIC_INTERFACE_VERSION_001 "STEAMMUSIC_INTERFACE_VERSION001"
#define STEAMMUSICREMOTE_INTERFACE_VERSION_001 "STEAMMUSICREMOTE_INTERFACE_VERSION001"
#define STEAMHTMLSURFACE_INTERFACE_VERSION_001 "STEAMHTMLSURFACE_INTERFACE_VERSION_001"
#define STEAMHTMLSURFACE_INTERFACE_VERSION_002 "STEAMHTMLSURFACE_INTERFACE_VERSION_002"
#define STEAMHTMLSURFACE_INTERFACE_VERSION_003 "STEAMHTMLSURFACE_INTERFACE_VERSION_003"
#define STEAMHTMLSURFACE_INTERFACE_VERSION_004 "STEAMHTMLSURFACE_INTERFACE_VERSION_004"
#define STEAMHTMLSURFACE_INTERFACE_VERSION_005 "STEAMHTMLSURFACE_INTERFACE_VERSION_005"
#define STEAMPARENTALSETTINGS_INTERFACE_VERSION_001 "STEAMPARENTALSETTINGS_INTERFACE_VERSION001"
#define STEAMINPUT_INTERFACE_VERSION_001 "SteamInput001"
#define STEAMINPUT_INTERFACE_VERSION_002 "SteamInput002"
#define STEAMINPUT_INTERFACE_VERSION_005 "SteamInput005"
#define STEAMINPUT_INTERFACE_VERSION_006 "SteamInput006"
#define STEAMREMOTEPLAY_INTERFACE_VERSION_001 "STEAMREMOTEPLAY_INTERFACE_VERSION001"
#define STEAMREMOTEPLAY_INTERFACE_VERSION_002 "STEAMREMOTEPLAY_INTERFACE_VERSION002"
#define STEAMREMOTEPLAY_INTERFACE_VERSION_003 "STEAMREMOTEPLAY_INTERFACE_VERSION003"
#define STEAMNETWORKINGMESSAGES_INTERFACE_VERSION_001 "SteamNetworkingMessages001"
#define STEAMNETWORKINGMESSAGES_INTERFACE_VERSION_002 "SteamNetworkingMessages002"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_001 "SteamNetworkingSockets001"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_002 "SteamNetworkingSockets002"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_003 "SteamNetworkingSockets003"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_004 "SteamNetworkingSockets004"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_006 "SteamNetworkingSockets006"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_008 "SteamNetworkingSockets008"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_009 "SteamNetworkingSockets009"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_010 "SteamNetworkingSockets010"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_011 "SteamNetworkingSockets011"
#define STEAMNETWORKINGSOCKETS_INTERFACE_VERSION_012 "SteamNetworkingSockets012"
#define STEAMNETWORKINGUTILS_INTERFACE_VERSION_001 "SteamNetworkingUtils001"
#define STEAMNETWORKINGUTILS_INTERFACE_VERSION_002 "SteamNetworkingUtils002"
#define STEAMNETWORKINGUTILS_INTERFACE_VERSION_003 "SteamNetworkingUtils003"
#define STEAMNETWORKINGUTILS_INTERFACE_VERSION_004 "SteamNetworkingUtils004"
#define STEAMINVENTORY_INTERFACE_VERSION_001 "STEAMINVENTORY_INTERFACE_V001"
#define STEAMINVENTORY_INTERFACE_VERSION_002 "STEAMINVENTORY_INTERFACE_V002"
#define STEAMINVENTORY_INTERFACE_VERSION_003 "STEAMINVENTORY_INTERFACE_V003"
#define STEAMVIDEO_INTERFACE_VERSION_001 "STEAMVIDEO_INTERFACE_V001"
#define STEAMVIDEO_INTERFACE_VERSION_002 "STEAMVIDEO_INTERFACE_V002"
#define STEAMVIDEO_INTERFACE_VERSION_007 "STEAMVIDEO_INTERFACE_V007"

// Forward declarations
class ISteamClient;
class ISteamUser;
class ISteamFriends;
class ISteamUtils;
class ISteamMatchmaking;
class ISteamUserStats;
class ISteamApps;
class ISteamNetworking;
class ISteamRemoteStorage;
class ISteamScreenshots;
class ISteamHTTP;
class ISteamUnifiedMessages;
class ISteamController;
class ISteamUGC;
class ISteamAppList;
class ISteamMusic;
class ISteamMusicRemote;
class ISteamHTMLSurface;
class ISteamInventory;
class ISteamVideo;
class ISteamParentalSettings;
class ISteamInput;
class ISteamRemotePlay;
class ISteamNetworkingMessages;
class ISteamNetworkingSockets;
class ISteamNetworkingUtils;

// Steam API functions
extern "C"
{
    __declspec(dllexport) ESteamAPIInitResult SteamAPI_Init();
    __declspec(dllexport) void SteamAPI_Shutdown();
    __declspec(dllexport) void SteamAPI_RunCallbacks();
    __declspec(dllexport) bool SteamAPI_IsSteamRunning();
    __declspec(dllexport) void* SteamClient();
    __declspec(dllexport) void* SteamUser();
    __declspec(dllexport) void* SteamFriends();
    __declspec(dllexport) void* SteamUtils();
    __declspec(dllexport) void* SteamMatchmaking();
    __declspec(dllexport) uint32 SteamAPI_GetHSteamUser();
    __declspec(dllexport) uint32 SteamAPI_GetHSteamUserA();
    __declspec(dllexport) uint32 SteamAPI_GetHSteamPipe();
    __declspec(dllexport) uint32 SteamAPI_GetHSteamPipeA();
    __declspec(dllexport) const char* SteamAPI_GetSteamInstallPath();
    __declspec(dllexport) const char* SteamAPI_GetSteamInstallPathA();
    __declspec(dllexport) const char* SteamAPI_GetSteamUserBase();
    __declspec(dllexport) void* SteamAPI_CreateInterface(const char* pName, int* pReturnCode);
    
    // Additional API functions
    __declspec(dllexport) void* SteamGameServer();
    __declspec(dllexport) void SteamGameServer_Shutdown();
    __declspec(dllexport) void SteamGameServer_RunCallbacks();
    __declspec(dllexport) bool SteamGameServer_BSecure();
    __declspec(dllexport) uint64 SteamGameServer_GetSteamID();
    __declspec(dllexport) bool SteamGameServer_Init(uint32 unIP, uint16 usPort, uint16 usGamePort, uint16 usQueryPort, EServerMode eServerMode, const char* pchVersionString);
}

// Base interface class
class ISteamClient
{
public:
    virtual ~ISteamClient() {}
};

// SteamUser interface
class ISteamUser
{
public:
    virtual ~ISteamUser() {}
    
    // Returns the Steam user ID of the account
    virtual uint64 GetSteamID() = 0;
    
    // Returns true if the user is logged into Steam
    virtual bool BLoggedOn() = 0;
};

// SteamFriends interface
class ISteamFriends
{
public:
    virtual ~ISteamFriends() {}
    
    // Returns the local player's name
    virtual const char* GetPersonaName() = 0;
    
    // Sets the player name
    virtual void SetPersonaName(const char* pchPersonaName) = 0;
};

// SteamUtils interface
class ISteamUtils
{
public:
    virtual ~ISteamUtils() {}
    
    // Returns the number of seconds since the Unix epoch
    virtual uint32 GetSecondsSinceAppActive() = 0;
    
    // Returns the Steam universe this client is running in
    virtual uint32 GetConnectedUniverse() = 0;
};

// SteamMatchmaking interface
class ISteamMatchmaking
{
public:
    virtual ~ISteamMatchmaking() {}
    
    // Gets the number of active players
    virtual int GetFavoriteGameCount() = 0;
    
    // Adds a server to the list of favorites
    virtual bool AddFavoriteGame(uint32 nAppID, uint32 nIP, uint16 nConnPort, uint16 nQueryPort, uint32 unFlags, uint32 rTime32LastPlayedOnServer) = 0;
};

// Additional interface classes
class ISteamUserStats
{
public:
    virtual ~ISteamUserStats() {}
};

class ISteamApps
{
public:
    virtual ~ISteamApps() {}
};

class ISteamNetworking
{
public:
    virtual ~ISteamNetworking() {}
};

class ISteamRemoteStorage
{
public:
    virtual ~ISteamRemoteStorage() {}
};

class ISteamScreenshots
{
public:
    virtual ~ISteamScreenshots() {}
};

class ISteamHTTP
{
public:
    virtual ~ISteamHTTP() {}
};

class ISteamUnifiedMessages
{
public:
    virtual ~ISteamUnifiedMessages() {}
};

class ISteamController
{
public:
    virtual ~ISteamController() {}
};

class ISteamUGC
{
public:
    virtual ~ISteamUGC() {}
};

class ISteamAppList
{
public:
    virtual ~ISteamAppList() {}
};

class ISteamMusic
{
public:
    virtual ~ISteamMusic() {}
};

class ISteamMusicRemote
{
public:
    virtual ~ISteamMusicRemote() {}
};

class ISteamHTMLSurface
{
public:
    virtual ~ISteamHTMLSurface() {}
};

class ISteamInventory
{
public:
    virtual ~ISteamInventory() {}
};

class ISteamVideo
{
public:
    virtual ~ISteamVideo() {}
};

class ISteamParentalSettings
{
public:
    virtual ~ISteamParentalSettings() {}
};

class ISteamInput
{
public:
    virtual ~ISteamInput() {}
};

class ISteamRemotePlay
{
public:
    virtual ~ISteamRemotePlay() {}
};

class ISteamNetworkingMessages
{
public:
    virtual ~ISteamNetworkingMessages() {}
};

class ISteamNetworkingSockets
{
public:
    virtual ~ISteamNetworkingSockets() {}
};

class ISteamNetworkingUtils
{
public:
    virtual ~ISteamNetworkingUtils() {}
};

#endif // STEAM_API_H